export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    ME: '/auth/me',
    REFRESH_TOKEN: '/auth/refresh-token',
    CHANGE_PASSWORD: '/auth/change-password',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    LOGOUT: '/auth/logout',
    GOOGLE: '/auth/google',
    GOOGLE_CONFIG: '/auth/google/config',
    SAML_SSO: (code) => `/auth/saml/sso/${code}`,
    SAML_DEMO: '/auth/saml/demo',
  },
  EMPLOYEES: {
    BASE: '/employees',
    documents: (id) => `/employees/${id}/documents`,
    timeline: (id) => `/employees/${id}/timeline`,
    documentDelete: (empId, docId) => `/employees/${empId}/documents/${docId}`,
  },
  DEPARTMENTS: '/departments',
  POSITIONS: '/positions',
  ATTENDANCE: {
    BASE: '/attendance',
    CHECK_IN: '/attendance/check-in',
    CHECK_OUT: '/attendance/check-out',
    MY: '/attendance/my',
    TODAY: '/attendance/today',
    COMPANY_LOCATION: '/companies/attendance-location',
  },
  LEAVES: {
    BASE: '/leaves',
    MY: '/leaves/my',
    APPROVE: (id) => `/leaves/${id}/approve`,
    REJECT: (id) => `/leaves/${id}/reject`,
  },
  PAYROLLS: {
    BASE: '/payrolls',
    MY: '/payrolls/my',
    GENERATE: '/payrolls/generate',
    APPROVE: (id) => `/payrolls/${id}/approve`,
    MARK_PAID: (id) => `/payrolls/${id}/mark-paid`,
    EXPORT_EXCEL: (id) => `/payrolls/${id}/export/excel`,
    EXPORT_PDF: (id) => `/payrolls/${id}/export/pdf`,
  },
  JOBS: '/jobs',
  CANDIDATES: '/candidates',
  INTERVIEWS: {
    BASE: '/interviews',
    COMPLETE: (id) => `/interviews/${id}/complete`,
  },
  ASSETS: {
    BASE: '/assets',
    ASSIGN: (id) => `/assets/${id}/assign`,
    RETURN: (id) => `/assets/${id}/return`,
    HISTORY: (id) => `/assets/${id}/history`,
  },
  COURSES: {
    BASE: '/courses',
    ENROLL: (courseId) => `/courses/${courseId}/enroll`,
  },
  ENROLLMENTS: {
    BASE: '/training-enrollments',
    STATUS: (id) => `/training-enrollments/${id}/status`,
  },
  PERFORMANCE: {
    BASE: '/performance',
    MY: '/performance/my',
    PUBLISH: (id) => `/performance/${id}/publish`,
    SELF_REVIEW: (id) => `/performance/${id}/self-review`,
    FINALIZE: (id) => `/performance/${id}/finalize`,
  },
  DATA_HUB: {
    EXPORT_EMPLOYEES: '/data-hub/export/employees',
    IMPORT_TEMPLATE: '/data-hub/import/template',
    IMPORT_EMPLOYEES: '/data-hub/import/employees',
  },
  CUSTOM_ROLES: {
    BASE: '/custom-roles',
    ROLE: (id) => `/custom-roles/${id}`,
    ASSIGN: (userId) => `/custom-roles/assign/${userId}`,
  },
  NOTIFICATIONS: {
    BASE: '/notifications',
    UNREAD: '/notifications/unread-count',
    READ: (id) => `/notifications/${id}/read`,
    READ_ALL: '/notifications/read-all',
  },
  DASHBOARD: {
    SUMMARY: '/dashboard/summary',
    EMPLOYEE_CHART: '/dashboard/employee-chart',
    PAYROLL_CHART: '/dashboard/payroll-chart',
    RECRUITMENT_CHART: '/dashboard/recruitment-chart',
    LEAVE_CHART: '/dashboard/leave-chart',
    ACTIVITIES: '/dashboard/activities',
  },
  SEARCH: '/search',
  ACTIVITY_LOGS: '/activity-logs',
  AUDIT_LOGS: {
    BASE: '/audit-logs',
    EXPORT: '/audit-logs/export',
  },
  COMPANIES: {
    MY: '/companies/my',
    SWITCH: '/companies/switch',
    SETTINGS: '/companies/settings',
    ATTENDANCE_LOCATION: '/companies/attendance-location',
  },
  BILLING: {
    CHECKOUT: '/billing/checkout',
    CONFIRM: '/billing/checkout/confirm',
    INVOICES: '/billing/invoices',
  },
  USER_PREFERENCES: {
    NOTIFICATIONS: '/users/preferences/notifications',
  },
  INTEGRATIONS: {
    API_KEYS: '/integrations/api-keys',
    API_KEY: (id) => `/integrations/api-keys/${id}`,
    WEBHOOKS: '/integrations/webhooks',
    WEBHOOK: (id) => `/integrations/webhooks/${id}`,
    WEBHOOK_TEST: (id) => `/integrations/webhooks/${id}/test`,
    WEBHOOK_DELIVERIES: '/integrations/webhooks/deliveries',
    SAML: '/integrations/saml',
  },
  SUBSCRIPTION: {
    BASE: '/subscription',
    UPGRADE: '/subscription/upgrade',
  },
  ONBOARDING: {
    STATUS: '/onboarding/status',
    STEP: '/onboarding/step',
    COMPLETE: '/onboarding/complete',
  },
  ANALYTICS: {
    BASE: '/analytics',
    EXPORT: '/analytics/export',
  },
  MOBILE: {
    SUMMARY: '/mobile/summary',
  },
  AI: {
    CONFIG: '/ai/config',
    INSIGHTS: '/ai/insights',
    CHAT: '/ai/chat',
  },
  PUSH: {
    CONFIG: '/push/config',
    REGISTER: '/push/register',
    UNREGISTER: '/push/unregister',
  },
  WORKFLOWS: {
    BASE: '/workflows',
    RULE: (id) => `/workflows/${id}`,
  },
  PERMISSIONS: {
    ME: '/permissions/me',
    MATRIX: '/permissions/matrix',
  },
  ANNOUNCEMENTS: '/announcements',
  SCHEDULED_REPORTS: '/scheduled-reports',
  SCHEDULED_REPORT: (id) => `/scheduled-reports/${id}`,
  PUBLIC_CAREERS: {
    company: (code) => `/public/careers/${code}`,
    jobs: (code) => `/public/careers/${code}/jobs`,
    job: (code, id) => `/public/careers/${code}/jobs/${id}`,
    apply: (code, id) => `/public/careers/${code}/jobs/${id}/apply`,
  },
};
